### ISSUE TITLE
How to Install dependency

### ISSUE THREAD

**Issue by bookswon** [Taggu1/Habit-tracker#1]
Hello

I cannot run this project.
because 
`The getter 'createdStream' isn't defined for the type 'AwesomeNotifications'. (Documentation)  Try importing the library that defines 'createdStream', correcting the name to the name of an existing getter, or defining a getter or field named 'createdStream'.`

![스크린샷 2023-05-05 오후 1 18 24](https://user-images.githubusercontent.com/131976025/236376840-2b9605af-6b4b-4ae0-b88d-9c49cee33eb5.png)

- Clone the repo
  - `git clone https://github.com/Taggu1/Habit-tracker.git`
- Install the dependicies
  - `flutter pub get`
- Run it
  - `flutter run`

**Comment by Taggu1** [comment]
Hello @bookswon 

This issue was thrown due to a use of invalid getter in the code
in the main.dart file, remove these lines
![image](https://user-images.githubusercontent.com/81987232/236397001-9ace8900-bc5b-4d9b-a03f-bc3fa0256727.png)

or download the repo again after the last commit and it will work 

thanks for reporting
have a great day !

**Comment by Taggu1** [comment]
Hello @bookswon 

This issue was thrown due to a use of invalid getter in the code
in the main.dart file, remove these lines
![image](https://user-images.githubusercontent.com/81987232/236397001-9ace8900-bc5b-4d9b-a03f-bc3fa0256727.png)

or download the repo again after the last commit and it will work 

thanks for reporting
have a great day !

**Comment by bookswon** [comment]
Thank you~
There are 2 other issues.

1. Firebase major version

![스크린샷 2023-05-06 오전 6 51 42](https://user-images.githubusercontent.com/131976025/236574666-4d4e7c12-9ac7-4950-a296-5d6b416f906f.png)

I've been looking for a way to fix it by doing the following:
`flutter pub upgrade --major-versions `

2. lib/screens/add_habit_screen.dart:35:16

![스크린샷 2023-05-06 오전 6 56 05](https://user-images.githubusercontent.com/131976025/236575201-fe05e729-62e1-43fc-9be1-7b250f1242bf.png)

`final _time =
      TimeOfDay(hour: DateTime.now().hour, minute: DateTime.now().minute);`
to: 
`final _time =Time(hour: DateTime.now().hour, minute: DateTime.now().minute);`
